export type Note = {
  id?: string;
  title: string;
  description: string;
  class: string;
  subject: string;
  topic: string;
  tags: string[];
  pdfURL: string;
  uploaderId: string;
  uploaderName: string;
  uploaderEmail: string;
  uploadDate: unknown;
  downloadsCount: number;
  status: "pending" | "approved" | "rejected";
  thumbnailUrl?: string;
  board?: string;
  type?: string;
  keywords?: string[];
  likes?: number;
  views?: number;
  downloads?: number;
  saves?: number;
  reports?: number;
  pageCount?: number;
  fileSize?: number;
  fileName?: string;
  filePath?: string;
  updatedAt?: unknown;
};